### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ERROR_MISSING_OWNER'

### ISSUE THREAD

**Issue by lapointexavier** [lifted-studios/AutoCopyright#11]
Hi,

Freshly installed the plugin using Package Control under Ubuntu. Tried restarting Sublime as well, starting from a new shell, etc.

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./InsertCopyrightCommand.py", line 44, in run
  File "./CopyrightCommand.py", line 43, in handle_missing_owner_exception
AttributeError: 'module' object has no attribute 'ERROR_MISSING_OWNER'
```

**Comment by lee-dohm** [comment]
Thanks very much for the bug report!

**Comment by lapointexavier** [comment]
Auto updated with Package Control (gotta love this) and works now, thanks!
